---
title: ""
sidebar: false
toc: false
page-layout: full
format: html

listing:
  - id: recent-blog-listing
    contents:
      - "blog/*/index.qmd"
    sort: "date desc"
    type: grid
    max-items: 9
    page-size: 3
    categories: false
    sort-ui: false
    filter-ui: false
    fields: [title, image, date, categories]
---

We want to asses the effect of protected areas on the occupancy of the species. We hypothesize that several mammal species have benefited of the conservation actions provided by protected areas, so we expect a decreases in occupancy from the interior of the protected area to the exterior as a function of the distance to the protected area border. We used a multispecies occupancy model incorporating spatial autocorrelation, to asses occupancy as a function of the distance to the protected area border. 

To account for several ecological factors we also tested and included elevation and forest integrity index (FLII) as occupancy covariates. 

We used the newly developed R package `spOccupancy` as approach to modelling the probability of occurrence of each species as a function of fixed effects of measured environmental covariates and random effects designed to account for unobserved sources of spatial dependence (spatial autocorrelation). 

